### ISSUE TITLE
Environmental Variables

### ISSUE THREAD

**Issue by TheScree** [TheObsidian/obsidian-guildbot#7]
Need to remove bot token from repository listing.

**Comment by tylerdmace** [comment]
We should revoke the token and issue a new one or else blow this repo away and restart so there's no history.

**Comment by TheScree** [comment]
I sent you the new token in a Discord private message. Let me know if you need anything else to implement it.

**Comment by TheScree** [comment]
I implemented a config module that is ignored right now by github, the token is inside it.
